baseURL = 'https://cv.bex.computer'
languageCode = 'en-us'
title = 'Rebecca Nyx B.'
theme = 'typo'

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rebexie/"

[[params.social]]
name = "github"
url = "https://github.com/b3xie"
